# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78b7ac5b434a2d94f4caabedbd558eb8679c8a0d00c5c07e97868c7f64e4d111625e95bfe442358046fe18f8821d334ad6eff84ec28fd54f333475a4a414d861

test:
  secret_key_base: 885df3608a822a54d0f3b35e9a5d66360bb60548a0ae2d9fac23d292ef6eba3121337c39a7b02f25c55f7247b9ccaec4f5591a86564b209dd9b721afb49be199

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
